/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmoketestRouteImport } from './routes/smoketest'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as AdminEisenpakkettenRouteImport } from './routes/admin.eisenpakketten'
import { Route as ApiPublicSmoketestSprint4TriggerRouteImport } from './routes/api.public.smoketest-sprint4-trigger'
import { Route as ApiPublicSmoketestSprint4RouteImport } from './routes/api.public.smoketest-sprint4'

const SmoketestRoute = SmoketestRouteImport.update({
  id: '/smoketest',
  path: '/smoketest',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEisenpakkettenRoute = AdminEisenpakkettenRouteImport.update({
  id: '/admin/eisenpakketten',
  path: '/admin/eisenpakketten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmoketestSprint4TriggerRoute =
  ApiPublicSmoketestSprint4TriggerRouteImport.update({
    id: '/api/public/smoketest-sprint4-trigger',
    path: '/api/public/smoketest-sprint4-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmoketestSprint4Route =
  ApiPublicSmoketestSprint4RouteImport.update({
    id: '/api/public/smoketest-sprint4',
    path: '/api/public/smoketest-sprint4',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smoketest': typeof SmoketestRoute
  '/admin/eisenpakketten': typeof AdminEisenpakkettenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/public/smoketest-sprint4': typeof ApiPublicSmoketestSprint4Route
  '/api/public/smoketest-sprint4-trigger': typeof ApiPublicSmoketestSprint4TriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smoketest': typeof SmoketestRoute
  '/admin/eisenpakketten': typeof AdminEisenpakkettenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/public/smoketest-sprint4': typeof ApiPublicSmoketestSprint4Route
  '/api/public/smoketest-sprint4-trigger': typeof ApiPublicSmoketestSprint4TriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smoketest': typeof SmoketestRoute
  '/admin/eisenpakketten': typeof AdminEisenpakkettenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/public/smoketest-sprint4': typeof ApiPublicSmoketestSprint4Route
  '/api/public/smoketest-sprint4-trigger': typeof ApiPublicSmoketestSprint4TriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/smoketest'
    | '/admin/eisenpakketten'
    | '/projects/$projectId'
    | '/api/public/smoketest-sprint4'
    | '/api/public/smoketest-sprint4-trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/smoketest'
    | '/admin/eisenpakketten'
    | '/projects/$projectId'
    | '/api/public/smoketest-sprint4'
    | '/api/public/smoketest-sprint4-trigger'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/smoketest'
    | '/admin/eisenpakketten'
    | '/projects/$projectId'
    | '/api/public/smoketest-sprint4'
    | '/api/public/smoketest-sprint4-trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SmoketestRoute: typeof SmoketestRoute
  AdminEisenpakkettenRoute: typeof AdminEisenpakkettenRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ApiPublicSmoketestSprint4Route: typeof ApiPublicSmoketestSprint4Route
  ApiPublicSmoketestSprint4TriggerRoute: typeof ApiPublicSmoketestSprint4TriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smoketest': {
      id: '/smoketest'
      path: '/smoketest'
      fullPath: '/smoketest'
      preLoaderRoute: typeof SmoketestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eisenpakketten': {
      id: '/admin/eisenpakketten'
      path: '/admin/eisenpakketten'
      fullPath: '/admin/eisenpakketten'
      preLoaderRoute: typeof AdminEisenpakkettenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/smoketest-sprint4-trigger': {
      id: '/api/public/smoketest-sprint4-trigger'
      path: '/api/public/smoketest-sprint4-trigger'
      fullPath: '/api/public/smoketest-sprint4-trigger'
      preLoaderRoute: typeof ApiPublicSmoketestSprint4TriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/smoketest-sprint4': {
      id: '/api/public/smoketest-sprint4'
      path: '/api/public/smoketest-sprint4'
      fullPath: '/api/public/smoketest-sprint4'
      preLoaderRoute: typeof ApiPublicSmoketestSprint4RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SmoketestRoute: SmoketestRoute,
  AdminEisenpakkettenRoute: AdminEisenpakkettenRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiPublicSmoketestSprint4Route: ApiPublicSmoketestSprint4Route,
  ApiPublicSmoketestSprint4TriggerRoute: ApiPublicSmoketestSprint4TriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
